baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Lina's Portfolio"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
  mainSections = ["portfolio"]
  test = true

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Portfolio"
  url = "portfolio/"

  [[params.navlinks]]
  name = "Bio"
  url = "bio/"

  [[params.navlinks]]
  name = "CV"
  url = "cv/"

  [[params.navlinks]]
  name = "Get in touch"
  url = "contact/"